#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestPlugin.Views.TestPlugin
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.5.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/TestPlugin/Configure.cshtml")]
    public class Configure : System.Web.Mvc.WebViewPage<dynamic>
    {
        public Configure()
        {
        }
        public override void Execute()
        {
WriteLiteral("    <!DOCTYPE html>\r\n    <html");

WriteLiteral(" lang=\"en\"");

WriteLiteral(" xmlns=\"http://www.w3.org/1999/xhtml\"");

WriteLiteral(">\r\n    <head>\r\n       \r\n        <meta");

WriteLiteral(" charset=\"utf-8\"");

WriteLiteral(" />    \r\n        <title></title>\r\n    </head>\r\n    <body>\r\n        <h1>");

            
            #line 9 "..\..\Views\TestPlugin\Configure.cshtml"
       Write(Model.MyProperty);

            
            #line default
            #line hidden
WriteLiteral("</h1>\r\n");

            
            #line 10 "..\..\Views\TestPlugin\Configure.cshtml"
        
            
            #line default
            #line hidden
            
            #line 10 "..\..\Views\TestPlugin\Configure.cshtml"
          Html.Raw(Scripts.testplugin);
            
            #line default
            #line hidden
WriteLiteral("\r\n    </body>\r\n    </html>\r\n\r\n\r\n\r\n");

        }
    }
}
#pragma warning restore 1591
